# Generated by Django 4.0.8 on 2023-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('current_usage', models.IntegerField(default=0)),
                ('month_usage_last_reset', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'engine',
                'verbose_name_plural': 'engines',
            },
        ),
    ]
