# Generated by Django 4.0.8 on 2023-04-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honyaku_assist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='month_usage_last_reset',
            new_name='created_on',
        ),
    ]
