# Generated by Django 4.0.8 on 2023-04-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honyaku_assist', '0002_rename_month_usage_last_reset_engine_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engine',
            name='created_on',
        ),
        migrations.AddField(
            model_name='engine',
            name='usage_last_reset_month',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='engine',
            name='usage_last_reset_year',
            field=models.IntegerField(default=2023),
        ),
    ]
