# Generated by Django 4.0.8 on 2023-04-15 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('honyaku_assist', '0003_remove_engine_created_on_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engine',
            old_name='usage_last_reset_month',
            new_name='month_usage_last_reset',
        ),
        migrations.RenameField(
            model_name='engine',
            old_name='usage_last_reset_year',
            new_name='year_usage_last_reset',
        ),
    ]
