# Generated by Django 4.0.8 on 2023-06-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honyaku_assist', '0004_rename_usage_last_reset_month_engine_month_usage_last_reset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='month_usage_last_reset',
            field=models.IntegerField(default=6),
        ),
    ]
