name: Run tests
on: push
env:
  SECRET_KEY: ${{secrets.SECRET_KEY}}
  DEBUG: ${{secrets.DEBUG}}
  ALLOWED_HOSTS: ${{secrets.ALLOWED_HOSTS}}
  CSRF_TRUSTED_ORIGINS: ${{secrets.CSRF_TRUSTED_ORIGINS}}
  DEEPL_AUTH_KEY: ${{secrets.DEEPL_AUTH_KEY}}
jobs:
  execute_tests:
    name: Install requirements and execute tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install pip
        run: sudo apt install python3-pip
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Execute tests
        run: python manage.py test -v 2 --settings=core.settings_github_tests
